<?xml version="1.0" encoding="utf-8"?><Database Name="QLKho" Class="QLKhoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLKho;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLKhoConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietPhieuNhap" Member="ChiTietPhieuNhaps">
    <Type Name="ChiTietPhieuNhap">
      <Column Name="MaCT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="HangHoa_ChiTietPhieuNhap" Member="HangHoa" ThisKey="MaHH" OtherKey="MaHH" Type="HangHoa" IsForeignKey="true" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="PhieuNhap" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="PhieuNhap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangHoa" Member="HangHoas">
    <Type Name="HangHoa">
      <Column Name="MaHH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MaNH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XuatXu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HangHoa_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaHH" OtherKey="MaHH" Type="ChiTietPhieuNhap" />
      <Association Name="LoaiHang_HangHoa" Member="LoaiHang" ThisKey="MaNH" OtherKey="MaNH" Type="LoaiHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kho" Member="Khos">
    <Type Name="Kho">
      <Column Name="MaKho" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKho" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Kho_PhieuNhap" Member="PhieuNhaps" ThisKey="MaKho" OtherKey="MaKho" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHang" Member="LoaiHangs">
    <Type Name="LoaiHang">
      <Column Name="MaNH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LoaiHang_HangHoa" Member="HangHoas" ThisKey="MaNH" OtherKey="MaNH" Type="HangHoa" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="QuanTriVien" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_PhieuNhap" Member="PhieuNhaps" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="MaPhieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoPhieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PhieuNhap_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="ChiTietPhieuNhap" />
      <Association Name="Kho_PhieuNhap" Member="Kho" ThisKey="MaKho" OtherKey="MaKho" Type="Kho" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuNhap" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>